dafi <- "./ExData_Plotting1/household_power_consumption.txt"
dat <- read.table(dafi, header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
subset <- dat[dat$Date %in% c("1/2/2007","2/2/2007") ,]
#str(subset)
datetime <- strptime(paste(subset$Date, subset$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
glacpo <- as.numeric(subset$Global_active_power)
glrepo <- as.numeric(subset$Global_reactive_power)
voltage <- as.numeric(subset$Voltage)
meter1 <- as.numeric(subset$Sub_metering_1)
meter2 <- as.numeric(subset$Sub_metering_2)
meter3 <- as.numeric(subset$Sub_metering_3)
png("plot4.png", width=480, height=480)
par(mfrow = c(2, 2))
plot(datetime, glacpo, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(datetime, voltage, type="l", xlab="datetime", ylab="Voltage")
plot(datetime, meter1, type="l", ylab="Energy Submetering", xlab="")
lines(datetime, meter2, type="l", col="red")
lines(datetime, meter3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o")
plot(datetime, glrepo, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()